import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Script from "next/script";
import 'bootstrap/dist/css/bootstrap.css';
import "../node_modules/bootstrap/dist/css/bootstrap.min.css";
import '../node_modules/font-awesome/css/font-awesome.css';
import "./globals.scss";
import Nav from "./components/Nav";
import Footer from "./components/Footer";
const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Nav/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
